package:
  name: remixt
  version: '0.5.4'

source:
  git_url: https://dranew@bitbucket.org/dranew/remixt.git
  git_rev: v0.5.4

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - boost_source ==1.60.0
    - zlib
    - bzip2

  run:
    - python
    - numpy
    - scipy
    - zlib
    - bzip2
    - pandas >=0.17.1
    - pytables
    - pypeliner >=0.4.1
    - statsmodels
    - scikit-learn
    - pyyaml
    - matplotlib
    - seaborn
    - bokeh >=0.11.1
    - shapeit

about:
  home: http://bitbucket.org/dranew/remixt
  summary: 'ReMixT is a tool for joint inference of clone specific segment and breakpoint copy number in whole genome sequencing data'
  license: MIT
  license_file: LICENSE

