#{% set data = load_setup_py_data() %}

package:
  name: remixt
  version: 0.5.19
#  version: {{ data.get('version') }}

source:
  git_url: https://github.com/amcpherson/remixt.git
  git_rev: v0.5.19
#  git_rev: v{{ data.get('version') }}
#  path: ../../

build:
  number: 0

requirements:
  build:
    - python ==3.10.4
    - cython
    - numpy ==1.22.3
    - boost_source ==1.60.0
    - zlib ==1.2.12
    - bzip2 ==1.0.8

  run:
    - python ==3.10.4
    - numpy ==1.22.3
    - scipy
    - zlib ==1.2.12
    - bzip2 ==1.0.8
    - pandas ==1.4.2
    - pytables ==3.7.0
    - pypeliner ==0.6.2
    - statsmodels ==0.13.2
    - scikit-learn ==1.0.1
    - pyyaml ==6.0
    - matplotlib ==3.5.1
    - seaborn ==0.11.2
    - bokeh ==2.4.2
    - shapeit ==2.r904
    - samtools ==1.6

about:
  home: http://bitbucket.org/dranew/remixt
  summary: 'ReMixT is a tool for joint inference of clone specific segment and breakpoint copy number in whole genome sequencing data'
  license: MIT
  license_file: LICENSE

